export const projects = [
  {
    title: 'Omnifood AI Based Diet Plan',
    description: "Using HTML and CSS I have learned how to build a responsive single paged website - from start to finish. The website is called Omnifood AI and it is a simple social media app that allows users to choose a diet plan interesting to their lives.",
      image: '/images/1.png',
      tags: ['HTML', 'CSS', 'Node'],
    source: 'https://omnifood-shafinul.netlify.app/',
    visit: 'https://github.com/SpJishan/',
    id: 0,
  },
  {
    title: 'Natours Travel With Comfort',
    description:"While building it I have learnt advanced CSS & SCSS, as well as how to use nested CSS. On top of that, at the end of the practice, I have this unique and complex website. And trust me, Tour based applications are impressive.",
    image: '/images/2.png',
    tags: [ 'HTML', 'CSS', 'SASS', 'Nested CSS', 'Node'],
    source: 'https://shafinultourapp.netlify.app/',
    visit: 'https://github.com/SpJishan/tour_app/tree/main',
    id: 1,
  },
  {
    title: 'Trillo All In One Flight Plan',
    description: "Using semantic HTML and nested CSS I designed all in one Booking Website. In this website, I use HTML, CSS, SASS and also nested CSS",
      image: '/images/3.png',
      tags: ['HTML', 'CSS', 'SASS', 'Nested CSS', 'Node'],
    source: 'https://trillobyspjishan.netlify.app/',
    visit: 'https://github.com/SpJishan/trillo-test',
    id: 2,
  },
  {
    title: 'Shortly Get Your Link Shortened',
    description: "I designed a link shortened website Using semantic HTML and TailwindCSS .More than just shorter links. Building brand's recognition ",
    image: '/images/4.png',
    tags: ['HTML', 'CSS', 'TailwindCSS' , 'Node'],
    source: 'https://shortlybyshafinul.netlify.app/',
    visit: 'https://github.com/SpJishan/Shortly',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2010, text: 'Started my journey as Graphics Designer', },
  { year: 2012, text: 'Designed and sold some logo , icon, cover image for 3 years', },
  { year: 2014, text: 'Started teaching job both in as private tuitor and as mentor in coaching centre for next 6 years', },
  { year: 2017, text: 'Started my journey as web developer', },
  { year: 2018, text: 'Started learning After effect , Premiare pro for promotional video editing', },
  { year: 2019, text: 'Founded JavaScript Mastery, Learning programming in web platform through React with HTML, CSS, Javascript', },
  { year: 2020, text: 'Practiced React.js , Also starded learning professional and advanced CSS Design', },
  { year: 2021, text: 'Building my projects and start to contribute in github', },
  { year: 2022, text: 'Started in Office job as It manager ', },
  { year: 2022, text: 'In Office Job at Lamda Telecom , LivinHub Technologies as a Grahics Designer ', },
  { year: 2023, text: 'In Office Job at Nur tech as a Grahics Designer, also at Maroon Clothings as Business Manager', },
  { year: 2023, text: 'Uploading my projects at netlify and github repo', },
];